apiVersion: apps/v1
kind: Deployment
metadata:
  name: uwb-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uwb-app
  template:
    metadata:
      labels:
        app: uwb-app
    spec:
      containers:
      - name: uwb-app-container
        # Zastąp poniższy URL swoim, jeśli używasz innego obrazu
        image: us-central1-docker.pkg.dev/hopeful-keep-480204-e0/uwb/uwb_app:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
