name: Deploy to Kubernetes
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "k8s/*"
          target: "~/"
      - name: Deploy on K8s
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            # Tworzymy plik klucza z tekstu zapisanego w Secrets
            echo '${{ secrets.K8S_KEY }}' > ~/k8s_key.json
            
            # Wskazujemy kubectl, żeby użył tego klucza do autoryzacji
            export KUBECONFIG=~/k8s_key.json
            
            # Wdrażamy aplikację (bez sprawdzania online, co omija błąd connection refused)
            kubectl apply -f ~/k8s/deployment.yaml --validate=false
            kubectl apply -f ~/k8s/service.yaml --validate=false
