name: Deploy to Kubernetes
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "k8s/*"
          target: "~/"
      - name: Deploy on K8s
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            rm -f ~/k8s_key.json
            echo '${{ secrets.K8S_KEY }}' > ~/k8s_key.json
            chmod 600 ~/k8s_key.json
            export KUBECONFIG=~/k8s_key.json
            kubectl apply -f ~/k8s/deployment.yaml --validate=false
            kubectl apply -f ~/k8s/service.yaml --validate=false
            
            # 6. Sprawdzenie czy się udało
            kubectl get pods
